### ISSUE TITLE
panic with high concurrency when update from `3.13.2` to the latest version

### ISSUE THREAD

**Issue by ETZhangSX** [imroc/req#157]
After I updated to the latest version, my server panic when I used JMeter to do the benchmark. The following is the stack info. It seems like write to the map of `connLRU` of transport in multi goroutine.

```go
fatal error: concurrent map writes

goroutine 7106 [running]:

runtime.throw({0x1166b1f?, 0xc29867?})
  /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000692e40 sp=0xc000692e10 pc=0x438991
runtime.mapdelete_fast64(0x9a8364c?, 0xeda95179e?, 0xc000d2afc0)
  /usr/local/go/src/runtime/map_fast64.go:282 +0x2dd fp=0xc000692e88 sp=0xc000692e40 pc=0x41283d
github.com/imroc/req/v3.(*connLRU).remove(...)
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/transport.go:3305
github.com/imroc/req/v3.(*Transport).queueForIdleConn(0xc0008f02c0, 0xc000455970)
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/transport.go:1221 +0x5f5 fp=0xc000692f78 sp=0xc000692e88 pc=0xc22d35
github.com/imroc/req/v3.(*Transport).getConn(0xc0008f02c0, 0xc000b8ab00, {{}, 0x0, {0xc0000fe5f0, 0x4}, {0xc0007a1400, 0x1f}, 0x0})
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/transport.go:1499 +0x37d fp=0xc000693190 sp=0xc000692f78 pc=0xc2439d
github.com/imroc/req/v3.(*Transport).roundTrip(0xc0008f02c0, 0xc000c77900)
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/transport.go:787 +0xc74 fp=0xc000693418 sp=0xc000693190 pc=0xc206d4
github.com/imroc/req/v3.(*Transport).RoundTrip(0xc0008f02c0, 0x13f5040?)
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/roundtrip.go:25 +0x47 fp=0xc000693468 sp=0xc000693418 pc=0xc16147
net/http.send(0xc000c77800, {0x13f5040, 0xc0008f02c0}, {0x110c260?, 0x4c1201?, 0x1c96820?})
  /usr/local/go/src/net/http/client.go:252 +0x5d8 fp=0xc000693648 sp=0xc000693468 pc=0x75fc58
net/http.(*Client).send(0xc000a29a40, 0xc000c77800, {0x20?, 0x1?, 0x1c96820?})
  /usr/local/go/src/net/http/client.go:176 +0x9b fp=0xc0006936c0 sp=0xc000693648 pc=0x75f4fb
net/http.(*Client).do(0xc000a29a40, 0xc000c77800)
  /usr/local/go/src/net/http/client.go:725 +0x8f5 fp=0xc0006938c0 sp=0xc0006936c0 pc=0x761935
net/http.(*Client).Do(...)
  /usr/local/go/src/net/http/client.go:593
github.com/imroc/req/v3.(*Client).roundTrip(0xc00056f900, 0xc0005c6960)
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/client.go:1278 +0x717 fp=0xc0006939b0 sp=0xc0006938c0 pc=0xc070b7
github.com/imroc/req/v3.(*Client).do(0xc00056f900, 0xc0005c6960)
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/client.go:1332 +0x167 fp=0xc000693a50 sp=0xc0006939b0 pc=0xc076a7
github.com/imroc/req/v3.(*Request).Do(0xc0005c6960, {0x0?, 0x1172b43?, 0x1f?})
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/request.go:505 +0x27c fp=0xc000693ae8 sp=0xc000693a50 pc=0xc1189c
github.com/imroc/req/v3.(*Request).Send(...)
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/request.go:514
github.com/imroc/req/v3.(*Request).Post(0xc00007bea4?, {0xc000151830?, 0xc00007bea9?})
  /root/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/request.go:545 +0x86 fp=0xc000693b18 sp=0xc000693ae8 pc=0xc11d86
```

For each request, I load options by the following func, which will clone a new client for request:

```go
func loadOptions(c *req.Client, opts []Option) *req.Client {
	if len(opts) == 0 {
		return c
	}
	c = c.Clone()
	for _, opt := range opts {
		opt(c)
	}
	return c
}
```

I even clone a new client before requesting, but it still panics.

```go
resp, err := c.Clone().R().SetContext(ctx).SetBodyJsonBytes(r.jsonBody()).Post(r.path())
```

But everything work normally when I rollback to `3.13.2`

**Comment by ETZhangSX** [comment]
It might be something wrong in transport's `Clone`

https://github.com/imroc/req/blob/1cf597212cc8d7918ef0c2c473f13eec035f8133/transport.go#L579-L600

**Comment by imroc** [comment]
Nice catch, the key point is struct copy:
```go
tt := *t 
```
It will copy the private fields, including `connLRU`, I will fix it as soon as possible.

**Comment by imroc** [comment]
`Client.Clone` is rarely used, why is it necessary to create a client for each request? what is the scenario.

**Comment by ETZhangSX** [comment]
> `Client.Clone` is rarely used, why is it necessary to create a client for each request? what is the scenario.

In our scenario, we need to set different timeout or headers for different params in each request.

**Comment by imroc** [comment]
You can upgrade to the latest version to resolve this problem:
```go
go get -u github.com/imroc/req/v3
```

**Comment by imroc** [comment]
> In our scenario, we need to set different timeout or headers for different params in each request.

I understand, but you still don't need to create the client each request, I'll give you an example:

```go
package main

import (
	"context"
	"github.com/imroc/req/v3"
	"time"
)

func main() {
	req.DevMode()

	timeoutCtx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	req.SetContext(timeoutCtx).
		SetHeader("Accept", "application/json; charset=utf-8").
		MustGet("https://httpbin.org/get")
}
```

**Comment by ETZhangSX** [comment]
> > In our scenario, we need to set different timeout or headers for different params in each request.
> 
> I understand, but you still don't need to create the client each request, I'll give you an example:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"github.com/imroc/req/v3"
> 	"time"
> )
> 
> func main() {
> 	req.DevMode()
> 
> 	timeoutCtx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
> 	defer cancel()
> 
> 	req.SetContext(timeoutCtx).
> 		SetHeader("Accept", "application/json; charset=utf-8").
> 		MustGet("https://httpbin.org/get")
> }
> ```

OK, got it
