### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference: runtime error: invalid memory address or nil pointer dereference:

### ISSUE THREAD

**Issue by hoslo** [imroc/req#182]
```golang
runtime error: invalid memory address or nil pointer dereference: runtime error: invalid memory address or nil pointer dereference: 
goroutine 1874452 [running]:
sc/pkg/message.(*Server).doRegisterSubscriber.func1.1()
	/app/pkg/message/server.go:128 +0x69
panic({0x1099440, 0x1bf6f90})
	/usr/local/go/src/runtime/panic.go:838 +0x207
sc/internal/conf.NewHttpTracer.func1.1(0xc00d0701e0)
	/app/internal/conf/conf.go:139 +0x377
github.com/imroc/req/v3.RoundTripFunc.RoundTrip(0xc000161e00?, 0xc00d0701e0?)
	/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/client.go:1158 +0x1f
github.com/imroc/req/v3.(*Client).do(0xc000161e00, 0xc00d0701e0)
	/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/client.go:1330 +0x151
github.com/imroc/req/v3.(*Request).Do(0xc00d0701e0, {0x0?, 0x203000?, 0x10?})
	/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/request.go:505 +0x27c
github.com/imroc/req/v3.(*Request).Send(...)
	/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/request.go:514
github.com/imroc/req/v3.(*Request).Post(0xc0089f9a30?, {0x1251281?, 0xb?})
	/go/pkg/mod/github.com/imroc/req/v3@v3.19.1/request.go:545 +0x86
sc/internal/data/image.RecognizeText({0x13e0570?, 0xc010aeb3e0}, {0xc03846e000, 0xea53c, 0xea53d})
	/app/internal/data/image/util.go:113 +0x565
sc/internal/data/image.GetSize({0x13e0570?, 0xc010aeb3e0?}, {0xc03846e000?, 0xea53c?, 0xea53d?})
	/app/internal/data/image/util.go:133 +0x45
sc/internal/data.(*dataRepo).Enhance(0xc0004c00c0, {0x13e0570, 0xc010aeb3e0}, 0xc01280a720)
	/app/internal/data/image.go:87 +0x289
sc/internal/biz.(*ScUsecase).Enhance(...)
	/app/internal/biz/sc.go:55
sc/internal/service.(*NatsService).Enhance(0xc0004102b8, {0x13e0570, 0xc010aeb3e0}, 0x164?)
	/app/internal/service/nats.go:70 +0x6d
sc/pkg/message.(*Server).doRegisterSubscriber.func1(0xc01280a720)
	/app/pkg/message/server.go:149 +0x459
created by sc/pkg/message.(*Broker).Subscribe.func1
	/app/pkg/message/broker.go:178 +0x17d
```
```golang
req.DefaultClient().WrapRoundTripFunc(func(rt req.RoundTripper) req.RoundTripFunc {
		return func(req *req.Request) (resp *req.Response, err error) {
			span, _, err := tracer.CreateEntrySpan(req.Context(), req.RawURL, func(key string) (string, error) {
				return req.Headers.Get(key), nil
			})
			if err != nil {
				return nil, err
			}
			defer func() {
				span.End()
			}()
			const componentIDGOHttpClient = 5005
			span.SetComponent(componentIDGOHttpClient)

			span.Tag("kind", "client")
			span.Tag("component", "http")
			span.Tag("operation", req.RawURL)
			span.Tag("args", req.QueryParams.Encode())

			span.SetSpanLayer(agentv3.SpanLayer_Http)

			resp, err = rt.RoundTrip(req)
			if err != nil {
				_, stack := log.ExtractError(err)
				span.Error(time.Now(), stack)
			}
			span.Tag(go2sky.TagStatusCode, resp.Status) // /app/internal/conf/conf.go:139 this line
			return
		}
	})
```

**Comment by imroc** [comment]
I think it's been fixed in newer version, try upgrade to the latest version.

**Comment by hoslo** [comment]
> I think it's been fixed in newer version, try upgrade to the latest version.

problem still exists
```golang
runtime error: invalid memory address or nil pointer dereference: runtime error: invalid memory address or nil pointer dereference: 
goroutine 98354 [running]:
sc/pkg/message.(*Server).doRegisterSubscriber.func1.1()
	/app/pkg/message/server.go:128 +0x69
panic({0x10a0240, 0x1c03f90})
	/usr/local/go/src/runtime/panic.go:838 +0x207
sc/internal/conf.NewHttpTracer.func1.1(0xc0002330e0)
	/app/internal/conf/conf.go:139 +0x377
github.com/imroc/req/v3.RoundTripFunc.RoundTrip(0xc0000f7e00?, 0xc0002330e0?)
	/go/pkg/mod/github.com/imroc/req/v3@v3.25.0/client.go:1188 +0x1f
github.com/imroc/req/v3.(*Request).do(0xc0002330e0)
	/go/pkg/mod/github.com/imroc/req/v3@v3.25.0/request.go:546 +0x151
github.com/imroc/req/v3.(*Request).Do(0xc0002330e0, {0x0?, 0x10e5340?, 0x1217101?})
	/go/pkg/mod/github.com/imroc/req/v3@v3.25.0/request.go:515 +0x17f
github.com/imroc/req/v3.(*Request).Send(...)
	/go/pkg/mod/github.com/imroc/req/v3@v3.25.0/request.go:594
github.com/imroc/req/v3.(*Request).Post(0xc0002330e0?, {0x125598d?, 0x4?})
	/go/pkg/mod/github.com/imroc/req/v3@v3.25.0/request.go:625 +0x86
sc/internal/data/image.RemoveText({0x13e8870?, 0xc0063b09c0}, {0xc007832000, 0x6e6f0, 0x88000})
	/app/internal/data/image/util.go:88 +0x6f9
sc/internal/data.(*dataRepo).Enhance(0xc0004000a0, {0x13e8870, 0xc0063b09c0}, 0xc003bdf980)
	/app/internal/data/image.go:78 +0xd9
sc/internal/biz.(*ScUsecase).Enhance(...)
	/app/internal/biz/sc.go:55
sc/internal/service.(*NatsService).Enhance(0xc0002e8270, {0x13e8870, 0xc0063b09c0}, 0x164?)
	/app/internal/service/nats.go:70 +0x6d
sc/pkg/message.(*Server).doRegisterSubscriber.func1(0xc003bdf980)
	/app/pkg/message/server.go:149 +0x459
created by sc/pkg/message.(*Broker).Subscribe.func1
	/app/pkg/message/broker.go:178 +0x17d
```

my version v3.25.0

**Comment by hoslo** [comment]
> Try this: `resp.Status` ==> `resp.GetStatus()`.
> 
> resp.Status refers resp.Response.Status, and Response could be nil if request failed.

The problem is gone, thanks for the quick reply 😀
