### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mcoo** [imroc/req#187]
```golang
package downloader

import (
	"fmt"
	"testing"
	"time"

	"github.com/imroc/req/v3"
)

func TestDownload(t *testing.T) {
	req.DevMode().EnableDebugLog().R().SetOutputFile("./test.file").SetDownloadCallbackWithInterval(func(info req.DownloadInfo) {
		fmt.Printf("downloaded %.2f%%\n", float64(info.DownloadedSize)/float64(info.Response.ContentLength)*100.0)
	}, time.Second).Get("https://bmclapi2.bangbang93.com/assets/60/609fe1ad7765f15a862cd1fb6dcfde7c26f02044")
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x15e34e5]

goroutine 20 [running]:
testing.tRunner.func1.2({0x1635dc0, 0x1a3e300})
	G:/Program/go/src/testing/testing.go:1396 +0x485
testing.tRunner.func1()
	G:/Program/go/src/testing/testing.go:1399 +0x616
panic({0x1635dc0, 0x1a3e300})
	G:/Program/go/src/runtime/panic.go:890 +0x267
mlcgo/downloader.TestDownload.func1({0xc000196230, 0xaf})
	f:/project/mlcgo/downloader/downloader_test.go:13 +0x45
github.com/imroc/req/v3.(*Client).roundTrip.func1.1(0xaf)
	C:/Users/enjoy/go/pkg/mod/github.com/imroc/req/v3@v3.26.3/client.go:1290 +0x5b
github.com/imroc/req/v3.(*callbackReader).Read(0xc000070000, {0xc000282000, 0x751, 0x2000})
	C:/Users/enjoy/go/pkg/mod/github.com/imroc/req/v3@v3.26.3/middleware.go:310 +0x15c
github.com/imroc/req/v3/internal/dump.(*dumpReponseBodyReadCloser).Read(0xc000008090, {0xc000282000, 0x751, 0x2000})
	C:/Users/enjoy/go/pkg/mod/github.com/imroc/req/v3@v3.26.3/internal/dump/dump.go:34 +0x8c
net/http.(*cancelTimerBody).Read(0xc00006e020, {0xc000282000, 0x751, 0x2000})
```
当下载链接出现 重定向时 `Callback` 出现 `panic: runtime error: invalid memory address or nil pointer dereference`

![image](https://user-images.githubusercontent.com/26184088/205480963-ad71459a-77ec-4f7d-85c4-4cf666dd963f.png)

**Comment by imroc** [comment]
如果请求不成功，http.Response 可能为nil，info.Response.ContentLength 这个引用可能就会 panic，在callback里可以判断下

**Comment by mcoo** [comment]
```golang
func TestDownload(t *testing.T) {
	req.DevMode().EnableDebugLog().R().SetOutputFile("./test.file").SetDownloadCallbackWithInterval(func(info req.DownloadInfo) {
		if info.Response.Response != nil {
			fmt.Printf("downloaded %.2f%%\n", float64(info.DownloadedSize)/float64(info.Response.ContentLength)*100.0)
		}

	}, time.Second).Get("https://bmclapi2.bangbang93.com/assets/60/609fe1ad7765f15a862cd1fb6dcfde7c26f02044")
}
```
这样可以，但 Callback 函数不会被触发，如何在重定向后换取到下载进度呢？

**Comment by imroc** [comment]
哦，重定向下载这种，callback暂时不会生效，之前没考虑到，后面我想想如何解决

**Comment by imroc** [comment]
我又测了下，callback是会被触发的，302的时候以及下载过程中都会被触发，测试代码：
```go
package main

import (
	"fmt"
	"github.com/imroc/req/v3"
	"time"
)

func main() {
	req.R().SetOutputFile("./test.file").SetDownloadCallbackWithInterval(func(info req.DownloadInfo) {
		if info.Response.Response != nil {
			fmt.Printf("downloaded %.2f%%\n", float64(info.DownloadedSize)/float64(info.Response.ContentLength)*100.0)
		} else {
			fmt.Println("ignore nil response")
		}
	}, time.Second).Get("https://bmclapi2.bangbang93.com/assets/60/609fe1ad7765f15a862cd1fb6dcfde7c26f02044")
}
```

输出：
```txt
ignore nil response
downloaded 100.00%
```

**Comment by mcoo** [comment]
嗯 我也试了一下 是可以触发的，希望这里的判断给文档上加一下，防止踩坑
```golang
if info.Response.Response != nil {
    fmt.Printf("downloaded %.2f%%\n", float64(info.DownloadedSize)/float64(info.Response.ContentLength)*100.0)
}
```

**Comment by imroc** [comment]
嗯，文档已更新
