### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 88250** [imroc/req#338]
抱歉不太清楚重现步骤，是进程挂了以后看的日志：

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb40547]

goroutine 10779366 [running]:
net/http/httptrace.ContextClientTrace(...)
	/usr/lib/go-1.21/src/net/http/httptrace/trace.go:25
github.com/imroc/req/v3.(*Transport).dialConn(0xc000007860, {0x0, 0x0}, {{}, 0x0, {0xc000135550, 0x4}, {0xc001df0540, 0x1c}, 0x0})
	/root/go/pkg/mod/github.com/imroc/req/v3@v3.43.1/transport.go:2004 +0x2e7
github.com/imroc/req/v3.(*Transport).dialConnFor(0x0?, 0xc00116dad0)
	/root/go/pkg/mod/github.com/imroc/req/v3@v3.43.1/transport.go:1832 +0xbd
created by github.com/imroc/req/v3.(*Transport).queueForDial in goroutine 10779363
	/root/go/pkg/mod/github.com/imroc/req/v3@v3.43.1/transport.go:1796 +0x3cb
```

**Comment by imroc** [comment]
This is likely a nil pointer from an uninitialized response. Please provide a reproduction case and stack trace. If this occurs with latest master, please open a new issue.
