### ISSUE TITLE
调试时经常莫名其妙 panic

### ISSUE THREAD

**Issue by RonaldinhoL** [imroc/req#401]
```
runtime: VirtualAlloc of 824929886208 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x7ff6a6e9b8cb?, 0x340b2985000?})
	D:/Go/go1.21.3/src/runtime/panic.go:1077 +0x65 fp=0xdbbe3ff790 sp=0xdbbe3ff760 pc=0x7ff6a40a4325
runtime.sysUsedOS(0x2c000000000, 0xc011a72000)
	D:/Go/go1.21.3/src/runtime/mem_windows.go:83 +0x1c9 fp=0xdbbe3ff7f0 sp=0xdbbe3ff790 pc=0x7ff6a407fc09
runtime.sysUsed(0x7ff6a83355c0?, 0x2487eae91b0?, 0x110?)
	D:/Go/go1.21.3/src/runtime/mem.go:77 +0x36 fp=0xdbbe3ff820 sp=0xdbbe3ff7f0 pc=0x7ff6a407f5b6
runtime.(*mheap).allocSpan(0x7ff6a83355c0, 0x6008d39, 0x0, 0xdc?)
	D:/Go/go1.21.3/src/runtime/mheap.go:1351 +0x4a5 fp=0xdbbe3ff8d0 sp=0xdbbe3ff820 pc=0x7ff6a4092d45
runtime.(*mheap).alloc.func1()
	D:/Go/go1.21.3/src/runtime/mheap.go:968 +0x5f fp=0xdbbe3ff918 sp=0xdbbe3ff8d0 pc=0x7ff6a409225f
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
	D:/Go/go1.21.3/src/runtime/asm_amd64.s:509 +0x49 fp=0xdbbe3ff928 sp=0xdbbe3ff918 pc=0x7ff6a40d3509

goroutine 330 [running, locked to thread]:
runtime.systemstack_switch()
	D:/Go/go1.21.3/src/runtime/asm_amd64.s:474 +0x8 fp=0xc011c11cd8 sp=0xc011c11cc8 pc=0x7ff6a40d34a8
runtime.(*mheap).alloc(0xc011a72000?, 0x6008d39?, 0x0?)
	D:/Go/go1.21.3/src/runtime/mheap.go:962 +0x5b fp=0xc011c11d20 sp=0xc011c11cd8 pc=0x7ff6a40921bb
runtime.(*mcache).allocLarge(0xc01218a6a8?, 0xc011a70528, 0x44?)
	D:/Go/go1.21.3/src/runtime/mcache.go:234 +0x8a fp=0xc011c11d68 sp=0xc011c11d20 pc=0x7ff6a407e6ca
runtime.mallocgc(0xc011a70528, 0x0, 0x0)
	D:/Go/go1.21.3/src/runtime/malloc.go:1123 +0x3de fp=0xc011c11dd8 sp=0xc011c11d68 pc=0x7ff6a407371e
runtime.slicebytetostring(0xc011c89800?, 0x0, 0xc011a70528)
	D:/Go/go1.21.3/src/runtime/string.go:112 +0x77 fp=0xc011c11e08 sp=0xc011c11dd8 pc=0x7ff6a40bc997
github.com/imroc/req/v3.(*Response).String(0xc0118e2ea0)
	C:/Users/Ronaldinho/go/pkg/mod/github.com/imroc/req/v3@v3.43.7/response.go:213 +0x45 fp=0xc011c11e58 sp=0xc011c11e08 pc=0x7ff6a4cf31c5
debugCall256()
	D:/Go/go1.21.3/src/runtime/asm_amd64.s:1965 +0x38 fp=0xc011c11f68 sp=0xc011c11e58 pc=0x7ff6a40d2dd8
runtime.debugCallWrap2(0xc011c850e0?)
	D:/Go/go1.21.3/src/runtime/debugcall.go:255 +0x75 fp=0xc011c11fb0 sp=0xc011c11f68 pc=0x7ff6a406cf15
runtime.debugCallWrap1()
	D:/Go/go1.21.3/src/runtime/debugcall.go:207 +0x53 fp=0xc011c11fe0 sp=0xc011c11fb0 pc=0x7ff6a406ce73
runtime.goexit()
	D:/Go/go1.21.3/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc011c11fe8 sp=0xc011c11fe0 pc=0x7ff6a40d54e1
created by runtime.debugCallWrap in goroutine 249
	<autogenerated>:1 +0x25
```

**Comment by RonaldinhoL** [comment]
是因为这一行的问题吗？
github.com/imroc/req/v3.(*Response).String(0xc0118e2ea0)
        C:/Users/Ronaldinho/go/pkg/mod/github.com/imroc/req/v3@v3.43.7/response.go:213 +0x45 fp=0xc011c11e58 sp=0xc011c11e08 pc=0x7ff6a4cf31c5

看到调 resp.String() 导致崩溃了，但是看这异常栈我也不知道是哪里调用的，我的IDE也没有常驻的 watch 变量

**Comment by RonaldinhoL** [comment]
![image](https://github.com/user-attachments/assets/85f98951-9b97-46c2-9308-4291621a1e4c)
注意到，当进入函数，开始单步调试时，IDE试图显示返回变量的字符串表示，这时候有概率会触发崩溃

**Comment by RonaldinhoL** [comment]
似乎是 goland 的bug

**Comment by imroc** [comment]
> 似乎是 goland 的bug

可能是，因为如果 resp 是 req 返回的，永远不可能是 nil，即便有 error 也不会是 nil

**Comment by RonaldinhoL** [comment]
> fatal error: out of memory
> 
> 看报错是内存满了

 不是内存的问题，因为野指针它试图申请一个几十TB的内存空间

**Comment by imroc** [comment]
那估计就是goland 的 bug 了

**Comment by RonaldinhoL** [comment]
确定是goland的问题，从2024.3回滚到2024.2没有复现了
