### ISSUE TITLE
异常中止了，提示panic: mime: invalid media parameter

### ISSUE THREAD

**Issue by super-l** [imroc/req#94]
程序运行一段时间后，异常中止，提示：
panic: mime: invalid media parameter

goroutine 79 [running]:
github.com/imroc/req/v3.(*Transport).autoDecodeResponseBody(0xc00417f400, 0xc003cdbcb0)
        C:/Users/Administrator/go/pkg/mod/github.com/imroc/req/v3@v3.7.6/transport.go:309 +0x6dd
github.com/imroc/req/v3.(*Transport).handleResponseBody(0xc00417f400, 0xc003cdbcb0, 0xc00455d600)
        C:/Users/Administrator/go/pkg/mod/github.com/imroc/req/v3@v3.7.6/transport.go:277 +0x3c
github.com/imroc/req/v3.(*Transport).RoundTrip(0xc00417f400, 0xc00455d600, 0xc00417f400, 0xc07e9c60b1d18338, 0xe6e3cda1d)
        C:/Users/Administrator/go/pkg/mod/github.com/imroc/req/v3@v3.7.6/roundtrip.go:24 +0x9e
net/http.send(0xc000be8000, 0x1971860, 0xc00417f400, 0xc07e9c60b1d18338, 0xe6e3cda1d, 0x1e17320, 0xc003a11050, 0xc00495d690, 0x2, 0x8)
        D:/install/go1.15.14/src/net/http/client.go:252 +0x473
net/http.(*Client).send(0xc0017197a0, 0xc000be8000, 0xc07e9c60b1d18338, 0xe6e3cda1d, 0x1e17320, 0xc003a11050, 0x1, 0x2, 0x0)
        D:/install/go1.15.14/src/net/http/client.go:176 +0x105
net/http.(*Client).do(0xc0017197a0, 0xc000be8000, 0x0, 0x0, 0x0)
        D:/install/go1.15.14/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
        D:/install/go1.15.14/src/net/http/client.go:586
github.com/imroc/req/v3.(*Client).do(0xc001824000, 0xc0038d0300, 0xc004ba9940, 0xc7fc7f, 0x100)
        C:/Users/Administrator/go/pkg/mod/github.com/imroc/req/v3@v3.7.6/client.go:1330 +0x225
github.com/imroc/req/v3.(*Request).Send(0xc0038d0300, 0x18584bd, 0x3, 0xc00376b8a0, 0x15, 0x0, 0x0, 0x0)
        C:/Users/Administrator/go/pkg/mod/github.com/imroc/req/v3@v3.7.6/request.go:472 +0xc5
github.com/imroc/req/v3.(*Request).Get(...)
        C:/Users/Administrator/go/pkg/mod/github.com/imroc/req/v3@v3.7.6/request.go:499
xxx.net/xxx/library/mhttp.Get(0xc00376b8a0, 0x15, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

**Comment by imroc** [comment]
感谢反馈，已经修复，可以升级到最新 v3.7.7 版本

**Comment by super-l** [comment]
速度挺快，点个赞！
